---

- name: servery nginx
  hosts: webservers
  become: True
  tasks:
    - name: Sprawdzenie czy nginx zainstalowany
      package: name=nginx update_cache=yes

    - name: Skopiuj config
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Konfiguracja
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: Kopia index.html
      template: >
        src=index.html.j2
        dest=/usr/share/nginx/html/index.html

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
       
       
       
       
