---

- name: konfiguracja webserver'a ORKUZ nginx
  hosts: webservers
  become: True
  tasks:
    - name: spr nginx
      package: 
        name: nginx 
        update_cache: yes
        ### apt-get update

    - name: kopia configu
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: konfiguracja
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: kopia pliku index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Start nginx
      service: 
        name: nginx 
        state: restarted
        #
        #
        #- name: Restart nginx
        #  service: name=nginx state=restarted

- name: Git
  hosts: webservers
  become: yes
  tasks:
    - name: spr czy git zainstalowany
      ansible.builtin.stat:
        path: /usr/bin/git
      register: git_installed
    
    - name: zainstaluj Git
      ansible.builtin.package:
        name: git
        state: present
      when: git_installed.stat.exists == false


    - name: Clone Git repository
      git:
        repo: https://github.com/quqli87/ORKUZ
        dest: /home/vagrant/konfigi
        version: copy_configs
        clone: yes

...
