---

- name: konfiguracja webserver'a ORKUZ nginx
  hosts: webservers
  become: True
  tasks:
    - name: spr nginx
      package: 
        name: nginx 
        update_cache: yes

    - name: kopia configu
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: konfiguracja
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: kopia pliku index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Start nginx
      service: 
        name: nginx 
        state: restarted

- name: Git
  hosts: webservers
  become: yes
  tasks:
    - name: spr czy git zainstalowany
      ansible.builtin.stat:
        path: /usr/bin/git
      register: git_installed
    
    - name: zainstaluj Git
      ansible.builtin.package:
        name: git
        state: present
      when: git_installed.stat.exists == false


    - name: Clone Git repository
      git:
        repo: https://github.com/quqli87/ORKUZ
        dest: /home/vagrant/konfigi
        version: copy_configs
        clone: yes

    - name: INFO
      ansible.builtin.debug:
        msg: |
                dodaj manualnie linie z pliku konfigi/mod_to_bashrc.txt to .bashrc - spowoduje to dodanie default'owych aliasow z pliku konfigi/aliases.txt do twojego configu
                sprawdz konfiguracje
               
- name: aliasy
  hosts: webservers
  become: yes
  tasks:
    - name: stworz ~/.bashrc-personal jezeli go nie ma
      ansible.builtin.file:
        path: ~/.bashrc-personal
        state: touch
    
    - name: skopiuj aliases.txt to ~/.bashrc-personal
      ansible.builtin.shell: cp /home/vagrant/konfigi/aliases.txt /home/vagrant/.bashrc-personal
    
    - name: Source ~/.bashrc-personal
      ansible.builtin.shell: . ~/.bashrc-personal

    - name: Source ~/.bashrc
      ansible.builtin.shell: . ~/.bashrc
...
